### ISSUE TITLE
Adding new supported tokens — RGT, TRIBE, and FEI

### ISSUE THREAD

**Issue by nathanhleung** [rainbow-me/rainbow-token-list#81]
Hi, are you open to PRs adding new supported tokens? Specifically, I'm looking to add support for RGT (Rari Governance Token), TRIBE (Tribe Governance Token), and FEI (Tribe stablecoin).

**Comment by welps** [comment]
You can submit the tokens upstream in https://github.com/ethereum-lists/tokens and we will pull them. The list builds out every 6 hours.
